wip

diff --git a/dctk/libexec/help b/dctk/libexec/help
--- a/dctk/libexec/help
+++ b/dctk/libexec/help
@@ -6,70 +6,87 @@ readonly _dctk_help=loaded
 
 source kzn.bash
 
-defs usage_message <<'EOS'
-  Usage: %s <command> [<args>]
+help_globals() {
+  prog=${_DCTK_PROG:-dctk}
 
-  Some useful %s commands are:
-  %s
+  defs usage_message <<'EOS'
+    Usage: %s <command> [<args>]
 
-  See '%s help <command>' for information on a specific command.\n
+    Some useful %s commands are:
+    %s
+
+    See '%s help <command>' for information on a specific command.\n
 EOS
+  # shellcheck disable=SC2059
+  printf -v usage_message "$usage_message\n" "$prog" "$prog" '%s' "$prog"
+  printf -v error_message '%s: no such command %s%s%s\n' "$prog" \' '%s' \'
+}
 
-prog=${_DCTK_PROG:-dctk}
+help_main() {
+  # shellcheck disable=SC2034
+  local params=( command )
+  eval "$(passed params "$@")"
 
-error_message="%s: no such command '%s'"
-
-main() {
-  local command
   local file
   local libexec
 
   libexec=$(realpath "$BASH_SOURCE")
-  libexec=$(dirname "$libexec")
+  libexec=$(dirname libexec)
 
-  is_same_as --complete "${1:-}" && exec "$libexec"/commands
+  is_same_as --complete command && exec "$libexec"/commands
 
-  command=${1:-}
   case $command in
-    "" )
+    '' )
       # shellcheck disable=SC2059,SC2154
-      printf "$usage_message" "$prog" "$prog" "$(print_summaries "$libexec")" "$prog"
+      printf "$usage_message" "$(print_summaries libexec)"
       ;;
     * )
-      file=$(command_path "$command" "$libexec")
+      file=$(command_path command libexec)
       # shellcheck disable=SC2059
-      is_given "$file" || errexit "$(printf "$error_message\n" "$prog" "$command")"
-      print_help "$file"
+      is_given file || errexit "$(printf "$error_message" "$command")"
+      print_help file
       ;;
   esac
 }
 
 command_path() {
-  local command=$1
-  local libexec=$2
+  # shellcheck disable=SC2034
+  local params=( command libexec )
+  eval "$(passed params "$@")"
 
-  command -v "$libexec"/"$command" || command -v "$libexec"/sh-"$command" ||:
+  command -v "$libexec/$command" || command -v "$libexec"/sh-"$command" ||:
 }
 
 help() {
-  # shellcheck disable=SC2059
-  printf "$(awk '/^[^#]/{p=0} /^# Help:/{p=1} p' "$1" | sed "s/^# Help: //;s/^# //;s/^#//")" "$prog"
+  # shellcheck disable=SC2034
+  local params=( path )
+  eval "$(passed params "$@")"
+  # shellcheck disable=SC2059,SC2154
+  printf "$(awk '/^[^#]/{p=0} /^# Help:/{p=1} p' "$path" | sed "s/^# Help: //;s/^# //;s/^#//")" "$prog"
 }
 
 print_help() {
-  local file=$1
+  # shellcheck disable=SC2034
+  local params=( file )
+  eval "$(passed params "$@")"
+
   local help
   local usage
 
-  usage=$(usage "$file")
-  is_given "$usage" || { puts "Sorry, this command isn't documented yet."; return 0 ;}
-  puts "$usage"
-  help=$(help "$file")
-  is_given "$help" && printf "\n%s\n" "$help"
+  # shellcheck disable=SC2034
+  usage=$(usage file)
+  is_given usage || { puts "Sorry, this command isn't documented yet."; return 0 ;}
+  puts usage
+  help=$(help file)
+  is_given help && printf "\n%s\n" "$help"
   return 0
 }
 
 print_summaries() {
+  # shellcheck disable=SC2034
+  local params=( libexec )
+  eval "$(passed params "$@")"
+
   local -a commands
   local -a summaries
   local columns
@@ -77,7 +94,6 @@ print_summaries() {
   local file
   local format
   local index
-  local libexec=$1
   local longest_command=0
   local summary
   local summary_length
@@ -85,41 +101,58 @@ print_summaries() {
   columns=$(tput cols)
 
   for command in $("$libexec"/commands); do
-    file=$(command_path "$command" "$libexec")
-    ! is_symlink "$file" || continue
-    summary=$(summary "$file")
-    is_given "$summary" || continue
+    # shellcheck disable=SC2034
+    file=$(command_path command libexec)
+    ! is_symlink file || continue
+    summary=$(summary file)
+    is_given summary || continue
     commands+=( "$command" )
     summaries+=( "$summary" )
     longest_command=$(( ${#command} > longest_command ? ${#command} : longest_command ))
   done
 
+  # shellcheck disable=SC2034
   summary_length=$(( columns - longest_command - 5 ))
 
   for index in "${!commands[@]}"; do
     printf -v format "   %%-%ss  %%s\n" "$longest_command"
     # shellcheck disable=SC2059
     printf "$format" "${commands[$index]}" \
-      "$(truncate "$summary_length" "${summaries[$index]}")"
+      "$(truncate summary_length "${summaries[$index]}")"
   done
 }
 
 # shellcheck disable=SC2059
-summary() { printf "$(sed -n -e "s/^# Summary: \(.*\)/\1/p" "$1")" "$prog" ;}
+summary() {
+  # shellcheck disable=SC2034
+  local params=( path )
+  eval "$(passed params "$@")"
+  printf "$(sed -n -e "s/^# Summary: \(.*\)/\1/p" "$path")" "$prog"
+}
 
 truncate() {
-  local max_length=$1
-  local string=$2
+  # shellcheck disable=SC2034
+  local params=( max_length string )
+  eval "$(passed params "$@")"
 
-  (( ${#string} > max_length )) || { puts "$string"; return ;}
-  local length=$(( max_length - 3 ))
+  local length
+
+  # shellcheck disable=SC2154
+  (( ${#string} > max_length )) || { puts string; return ;}
+  length=$(( max_length - 3 ))
   puts "${string:0:$length}..."
 }
 
-# shellcheck disable=SC2059
-usage() { printf "$(sed -n "s/^# \(Usage: .*\)/\1/p" "$1")" "$prog" ;}
+usage() {
+  # shellcheck disable=SC2034
+  local params=( path )
+  eval "$(passed params "$@")"
+  # shellcheck disable=SC2059
+  printf "$(sed -n "s/^# \(Usage: .*\)/\1/p" "$path")" "$prog"
+}
 
 return 0 2>/dev/null ||:
 
 strict_mode on
-main "$@"
+help_globals
+help_main "$@"
diff --git a/dctk/libexec/init b/dctk/libexec/init
--- a/dctk/libexec/init
+++ b/dctk/libexec/init
@@ -5,33 +5,35 @@ readonly _dctk_init=loaded
 
 source kzn.bash
 
-prog=${_DCTK_PROG:-dctk}
+init_globals() {
+  defs error_message <<'EOS'
+    # Load %s automatically by adding
+    # the following to %s:
 
-defs error_message <<'EOS'
-  # Load %s automatically by adding
-  # the following to %s:
-
-  eval "$(%s/bin/%s init -)"
+    eval "$(%s/bin/%s init -)"
 EOS
+  # shellcheck disable=SC2059
+  printf -v error_message "$error_message\n" "$_DCTK_PROG" '%s' '%s' "$_DCTK_PROG"
 
-# shellcheck disable=SC2059
-printf -v error_message "$error_message\n" "$prog" '%s' '%s' "$prog"
-
-defs shell_format <<'EOS'
-  for file in %q/*.%s; do
-    source "$file"
-  done
-  unset -v file
+  defs shell_format <<'EOS'
+    for file in %q/*.%s; do
+      source "$file"
+    done
+    unset -v file
 EOS
+}
 
 init_main() {
+  # shellcheck disable=SC2034
+  local params=( option shell )
+  eval "$(passed params "$@")"
+
   local completions
   local libexec
   local path_format
   local print
   local profile
   local root
-  local shell
 
   libexec=$(realpath "$BASH_SOURCE")
   libexec=$(dirname "$libexec")
@@ -42,12 +44,17 @@ init_main() {
   printf -v error_message "$error_message" '%s' "$root"
 
   print=""
-  is_same_as - "${1:-}" && { print=1; shift ;}
+  # shellcheck disable=SC2034
+  if is_same_as - option; then
+    print=1
+  else
+    # shellcheck disable=SC2154
+    shell=$option
+  fi
 
-  shell=${1:-}
-  is_given "$shell" || shell=$(basename "$SHELL")
+  is_given shell || shell=$(basename "$SHELL")
 
-  ! is_given "$print" && {
+  ! is_given print && {
     case $shell in
       'bash' )
         # shellcheck disable=SC2088
@@ -65,7 +72,7 @@ init_main() {
     # shellcheck disable=SC2059
     printf -v error_message "$error_message" "$profile"
     # shellcheck disable=SC2059,SC2154
-    errexit "$error_message"
+    errexit error_message
   }
 
   # shellcheck disable=SC2016
@@ -74,7 +81,7 @@ init_main() {
   printf "$path_format\n" "$root"
 
   case $shell in
-    "bash" | "zsh" )
+    'bash' | 'zsh' )
       # shellcheck disable=SC2059,SC2154
       printf "$shell_format\n" "$completions" "$shell"
       ;;
@@ -84,4 +91,5 @@ init_main() {
 return 0 2>/dev/null ||:
 
 strict_mode on
+init_globals
 init_main "$@"
